site_name: My Docs
site_url: https://5ubstance.github.io/bitcoin-doc/
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/5ubstance
    - icon: fontawesome/brands/btc
      link: https://5ubstance.github.io/bitcoin-doc/assets/bitcoin.pdf
